name: quality_check

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: rust (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.timeout_minutes }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            timeout_minutes: 45
          - os: macos-latest
            timeout_minutes: 60
          - os: windows-latest
            timeout_minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install linux deps
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev libwayland-dev libx11-xcb-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libfontconfig-dev

      - name: install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: cargo check
        run: cargo +nightly check --workspace --all-targets --locked

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: cargo clippy
        run: cargo +nightly clippy --workspace --all-targets --locked -- -D warnings

      - name: cargo test
        run: cargo test --workspace --locked
